name: BUILD AND PUBLISH

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ğŸˆ Pull alpine:latest
        run: docker pull alpine:latest

      - name: ğŸ—ï¸ Build stale images
        run: make build FLUTTER_CHANNEL="stable"

      - name: âœ¨ Log into registry
        run: echo "${{ secrets.DOCKER_LOGIN_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN_USERNAME }} --password-stdin

      - name: ğŸ”¥ Push images to registry
        run: make build FLUTTER_CHANNEL="stable"

