name: Dispatch

on: workflow_dispatch

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Pull debian
        run: docker pull debian:stretch
        
      - name: Build stable image
        run: docker build . --file Dockerfile --build-arg flutter_version="stable" --tag plugfox/flutter:stable
        
      - name: Build beta image
        run: docker build . --file Dockerfile --build-arg flutter_version="beta" --tag plugfox/flutter:beta
        
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_LOGIN_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN_USERNAME }} --password-stdin

      - name: Push images
        run: |
          docker push plugfox/flutter:stable
          docker push plugfox/flutter:beta
