name: Docker

on:
  # Publish `master` as Docker `latest` image.
  #push:
  #  branches:
  #    - master
  schedule:
  #  - cron:  '0 7 * * 1'
    - cron: '10 14 * * *'

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    #if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Pull debian
        run: docker pull debian:stretch
        
      - name: Build stable image
        run: docker build . --file Dockerfile --build-arg flutter_version="stable" --tag plugfox/flutter:stable
        
      - name: Build beta image
        run: docker build . --file Dockerfile --build-arg flutter_version="beta" --tag plugfox/flutter:beta
        
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_LOGIN_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN_USERNAME }} --password-stdin

      - name: Push images
        run: |
          docker push plugfox/flutter:stable
          docker push plugfox/flutter:beta
